name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1 # Use ruby/setup-ruby to shorten build times, https://github.com/ruby/setup-ruby
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
